version: '3.8'

services:

  mysql:
    image: mysql:8.0.28
    container_name: evs1
    environment:
      - MYSQL_DATABASE=evs
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "3306:3306"
    restart: on-failure

  app_prod:
    image: ruky00/evsglobal
    ports:
      - "8443:8443"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:mysql://evs1:3306/evs
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - EMAIL_TFG=${EMAIL_TFG}
      - EMAIL_SERVICE=${EMAIL_SERVICE}
    depends_on:
      - mysql
    restart: on-failure

