name: Despliegue en EC2

on:
  workflow_run:
    workflows: ["Construir y Subir Imagen Docker"]
    types:
      - completed

jobs:
  build-and-push:
    runs-on: self-hosted

    env:
      EMAIL_SERVICE: ${{ secrets.EMAIL_SERVICE }}
      EMAIL_TFG: ${{ secrets.EMAIL_TFG }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Pull docker Image
        run: sudo docker pull ruky00/evsglobal
        
      - name: Delete old docker container
        run: sudo docker-compose down
        
     
      - name: Relanzar contenedor con la nueva imagen
        run: sudo docker-compose up -d

      
          
