name: Despliegue en EC2

on:
  workflow_run:
    workflows: ["Construir y Subir Imagen Docker"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Execute deployment script on EC2
        uses: easingthemes/ssh-deploy@v5.0.3
        with:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.EC2_HOST }}
          REMOTE_USER: ${{ secrets.EC2_USER }}
          
          SCRIPT_AFTER: |
            cd EnterpriseEventSolutions
            sudo ./cd.sh
