name: Despliegue en EC2

on:
  workflow_run:
    workflows: ["Construir y Subir Imagen Docker"]
    types:
      - completed

jobs:
  build-and-push:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Pull docker Image
        run: sudo docker pull ruky00/evsglobal
        
      - name: Delete old docker container
        run: sudo docker rm -f evs
        
      - name: Relanzar contenedor con la nueva imagen
        run: sudo docker-compose up 

      
          
